import { Noto_Sans } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Weather Now",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='h-[100%]'>
      <body className={notoSans.className + ' h-[100%] overflow-hidden'} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
